spring.application.name=finance-backend

spring.datasource.url=jdbc:postgresql://db.nfpjusprxbljduhmepkq.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=lUwqLIYDB4mpaspq

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
